---
- hosts: all

  become: yes
  become_method: sudo
  remote_user: ubuntu

  tasks:
   - name: Copy webapp to webserver
     copy:
        src: target/AnsibleCICD.war
        dest: /opt/tomcat/webapps/
