- name: launch aws ec2 instance
  hosts: localhost
 
  vars:
     key_name: sl_ansible
     ansible_python_interpreter: /usr/bin/python3

  tasks:
   - name: ec2 create keypair
     ec2_key:
        aws_access_key: "{{ my_access_key }}"
        aws_secret_key: "{{ my_secret_key }}"
        aws_security_token: "{{ my_security_token }}"
        name: "{{ key_name }}"
        region: us-east-1
     register: ec2_key_result
        # - debug:
        #      var: ec2_key.name
   - name: Create keys dir if not exist
     file:
        path: keys
        owner: jenkins
        group: jenkins
        mode: 0700
        state: directory
   - name: Store private key
     copy: content="{{ ec2_key_result.key.private_key }}" dest="keys/{{ key_name }}.pem" mode=0400
     when: ec2_key_result.changed

    