- name: launch aws ec2 instance
  hosts: localhost
 
  vars:
     key_name: sl_ansible

  tasks:
   - name: ec2 create keypair
     ec2_key:
        aws_access_key: "{{ my_access_key }}"
        aws_secret_key: "{{ my_secret_key }}"
        aws_security_token: "{{ my_security_token }}"
        name: "{{ key_name }}"
        region: us-east-1
     register: ec2_key_result
        # - debug:
        #      var: ec2_key.name
   - name: Store private key
     copy: content="{{ ec2_key_result.key.private_key }}" dest="~/.ssh/{{ key_name }}.pem" mode=0600
     when: ec2_key_result.changed

    