- name: fix 
  hosts: localhost

  vars:
    web_ip: 4.56.7.8
    key_name: "sl_ansible"

  tasks:
   - name: create example hosts file
     ansible.builtin.lineinfile:
      path: ex_hosts.ini
      line: "[web]"
      create: yes
      
   - name: add another line to the file
     ansible.builtin.lineinfile:
      path: "ex_hosts.ini"
      insertafter: "[web]"
      line: "{{ web_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/{{ key_name }}.pem ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"